server:
  port: 8090
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

# JWT 설정
jwt:
  jwtSecret: "aVeryLongSecretKeyThatIsAtLeast32BytesLongForSecurity"
  jwtExpirationMs: 3600000 # 1시간 (밀리초 단위)
  jwtRefreshExpirationMs: 86400000 # 24시간 (밀리초 단위)
  refreshTokenDurationMinutes: 1440 # 24시간 (분 단위)

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/linktalk
    username: root
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
#        use_sql_comments: true
        default_batch_fetch_size: 10
#        highlight_sql: true

  p6spy:
    filter:
      include: .* # 모든 SQL 쿼리를 P6Spy로 포함

file:
  upload-dir: /Users/your-username/Downloads # 파일이 저장될 경로
  url-prefix: http://localhost:8080/files # 파일 접근을 위한 URL prefix


logging:
  level:
    org.hibernate.SQL: DEBUG
#    org.hibernate.orm.jdbc.bind: TRACE
  pattern:
    console: "[%d{yyyy-MM-dd HH:mm:ss}] [%-5level] %logger{36} - %msg%n"
  ansi:
    output-enabled: true  # ANSI 컬러를 지원하는 경우에만 사용
