server:
  port: 8090
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

# JWT 설정
jwt:
  jwtSecret: "aVeryLongSecretKeyThatIsAtLeast32BytesLongForSecurity"
  jwtExpirationMs: 3600000 # 1시간 (밀리초 단위)
  jwtRefreshExpirationMs: 86400000 # 24시간 (밀리초 단위)
  refreshTokenDurationMinutes: 1440 # 24시간 (분 단위)

spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 10
        highlight_sql: true
        dialect: org.hibernate.dialect.H2Dialect
    database-platform: org.hibernate.dialect.H2Dialect
    database: h2
  p6spy:
    filter:
      include: .*

file:
  upload-dir: /Users/your-username/Downloads # 파일이 저장될 경로
  url-prefix: http://localhost:8080/files # 파일 접근을 위한 URL prefix